#!/usr/bin/env python3
"""
Minimal **pair-wise** Combinatorial Interaction Testing (CIT) demo.

Replaces the full Cartesian product with a 2-way (pair-wise) covering array
generated by the AllPairs algorithm from the *allpairspy* package.
"""

from typing import Dict, List, Iterator
from arlib.allpairspy import AllPairs


Parameters = Dict[str, List[str]]

# --------------------------------------------------------------------------- #
# Test-case generator                                                         #
# --------------------------------------------------------------------------- #
def generate_pairwise(parameters: Parameters) -> Iterator[Dict[str, str]]:
    """
    Yield dictionaries that form a 2-way covering array of *parameters*.

    >>> for case in generate_pairwise({...}): ...
    """
    keys = list(parameters)        # preserves insertion order (≥3.7)
    for row in AllPairs(parameters.values()):
        yield {k: v for k, v in zip(keys, row)}


# --------------------------------------------------------------------------- #
# Demo                                                                        #
# --------------------------------------------------------------------------- #
def main() -> None:
    parameters: Parameters = {
        "Browser": ["Chrome", "Firefox"],
        "OS":      ["Windows", "Linux"],
        "Screen":  ["Mobile", "Desktop"],
        # add more parameters/levels here ─ the generator scales well
    }

    print("Pair-wise covering array")
    print("-----------------------")
    for idx, test in enumerate(generate_pairwise(parameters), start=1):
        pretty = ", ".join(f"{k}: {v}" for k, v in test.items())
        print(f"Test Case {idx:2}: {{ {pretty} }}")


if __name__ == "__main__":
    main()
