# coding: utf-8
"""
Some facilities for converting between different forms of Boolean formulas
E.g., Tseitin's transformation

"""
from typing import List


def flatter(lst):
    """Misc for tseitin"""
    res = []
    for i in lst:
        abs_lst = [abs(j) for j in i]
        res.extend(abs_lst)
    return res


def tseitin(dnf: List[List]):
    """
    This function implements the Tseitin algorithm to generate a logical expression
    in CNF form that is equivalent to a given DNF (Disjunctive Normal Form) expression.

    Args:
    - dnf: A nested list of integers representing the DNF expression to be converted

    Returns:
    - A nested list of integers representing the CNF expression generated by Tseitin algorithm

    NOTE: Tseitin algorithm: may introduce auxiliary variables
    """
    maxi = max(flatter(dnf))
    next_one = maxi + 1
    ans = []
    for i in dnf:
        ans.append([-1 * i[j] for j in range(len(i))] + [next_one])
        for j in i:
            ans.append([j, -1 * next_one])
        next_one += 1
    return ans


def test():
    """test case"""
    dnf = [[-1, -2, 4], [1, -4], [2, -4], [3, 5], [-3, -5]]
    print(tseitin(dnf))


if __name__ == "__main__":
    test()
