from typing import Any, Generator, Iterator, TextIO

from .script import SmtLibCommand, SmtLibScript

class Tokenizer:
    generator: Generator[str, Any, None]
    def __init__(self, handle: TextIO, interactive: bool = False) -> None: ...

class SmtLibParser:
    def get_script(self, script: TextIO) -> SmtLibScript: ...
    def get_script_fname(self, script: str) -> SmtLibScript: ...
    def get_command_generator(self, script: TextIO) -> Iterator[SmtLibCommand]: ...
