"""
FIXME: to validate
 (this file is generated by LLM)
"""

from typing import List
import z3

from arlib.counting.bool.dimacs_counting import count_dimacs_solutions, \
    count_dimacs_solutions_parallel


def count_z3_models_by_enumeration(formula: z3.BoolRef, max_models: int = None) -> int:
    """
    Count models for a z3 Boolean formula.

    Args:
        formula (z3.BoolRef): The z3 formula to count models for
        max_models (int, optional): Maximum number of models to count

    Returns:
        int: Number of models found (-1 if exceeded max_models)
    """
    solver = z3.Solver()
    solver.add(formula)
    count = 0

    while solver.check() == z3.sat:
        count += 1
        if max_models and count > max_models:
            return -1

        model = solver.model()
        # Create blocking clause
        block = []
        for decl in model:
            if decl.arity() == 0 and decl.range().is_bool():
                val = model[decl]
                if z3.is_true(val):
                    block.append(decl() == False)
                else:
                    block.append(decl() == True)
        solver.add(z3.Or(block))

    return count


def z3_to_dimacs(formula: z3.BoolRef) -> tuple[List[str], List[str]]:
    """
    Convert a z3 formula to DIMACS format.

    Args:
        formula (z3.BoolRef): Z3 formula to convert

    Returns:
        tuple[List[str], List[str]]: Header and clauses in DIMACS format
    """
    # Convert to CNF
    goal = z3.Goal()
    goal.add(formula)
    tactic = z3.Then(z3.Tactic('simplify'),
                     z3.Tactic('tseitin-cnf'),
                     z3.Tactic('simplify'))
    result = tactic(goal)[0]

    # Handle tautology
    if len(result) == 0:
        # Empty CNF is a tautology - add a dummy variable with (x or not x)
        header = ["p cnf 1 2"]
        return header, ["1", "-1"]

    # Get variables and create mapping
    all_vars = set()
    for f in result:
        for v in z3.z3util.get_vars(f):
            all_vars.add(str(v))

        # Ensure at least one variable exists
    if not all_vars:
        header = ["p cnf 1 1"]
        return header, ["1"]  # Add a single true variable

    var_map = {name: idx + 1 for idx, name in enumerate(sorted(all_vars))}

    # Convert clauses
    dimacs_clauses = []
    for clause in result:
        if z3.is_or(clause):
            lits = clause.children()
        else:
            lits = [clause]

        dimacs_clause = []
        for lit in lits:
            if z3.is_not(lit):
                var_name = str(lit.children()[0])
                dimacs_clause.append(f"-{var_map[var_name]}")
            else:
                var_name = str(lit)
                dimacs_clause.append(str(var_map[var_name]))
        dimacs_clauses.append(" ".join(dimacs_clause))

    header = [f"p cnf {len(var_map)} {len(dimacs_clauses)}"]
    return header, dimacs_clauses


def count_z3_solutions(formula: z3.BoolRef, parallel: bool = False) -> int:
    """
    Count solutions for a z3 formula.

    Args:
        formula (z3.BoolRef): Z3 formula to count solutions for
        parallel (bool): Whether to use parallel counting

    Returns:
        int: Number of solutions
    """
    header, clauses = z3_to_dimacs(formula)
    if parallel:
        return count_dimacs_solutions_parallel(header, clauses)
    return count_dimacs_solutions(header, clauses)
