"""
FIXME: this file is generated by LLM..
Model Counting Meets Abstract Interpretation

This module implements the integration of model counting with abstract interpretation
techniques, including analysis of bit-vector overflow/underflow behaviors.

Additional Features:
- Overflow/underflow detection and analysis
- Impact assessment on model counting
- Comparison of wrapped vs unwrapped arithmetic
"""

import logging
from dataclasses import dataclass
from enum import Enum
from typing import List, Tuple, Optional, Dict, Set

import z3

from arlib.smt.bv.qfbv_counting import BVModelCounter
from arlib.symabs.omt_symabs.bv_symbolic_abstraction import BVSymbolicAbstraction
from arlib.tests.formula_generator import FormulaGenerator

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


class OverflowType(Enum):
    """Types of arithmetic overflow conditions"""
    NONE = 0
    OVERFLOW = 1
    UNDERFLOW = 2
    BOTH = 3


@dataclass
class OverflowResults:
    """
    Results from overflow/underflow analysis.

    Attributes:
        overflow_count: Number of overflow cases
        underflow_count: Number of underflow cases
        affected_vars: Variables affected by overflow/underflow
        impact_ratio: Ratio of models affected by overflow/underflow
    """
    overflow_count: int = 0
    underflow_count: int = 0
    affected_vars: Set[str] = None
    impact_ratio: float = 0.0

    def __post_init__(self):
        if self.affected_vars is None:
            self.affected_vars = set()


@dataclass
class AbstractionResults:
    """
    Stores results from different abstraction domains.

    Attributes:
        interval_fp_rate: False positive rate for interval domain
        zone_fp_rate: False positive rate for zone domain
        octagon_fp_rate: False positive rate for octagon domain
        overflow_results: Results from overflow analysis
    """
    interval_fp_rate: float = 0.0
    zone_fp_rate: float = 0.0
    octagon_fp_rate: float = 0.0
    overflow_results: Optional[OverflowResults] = None


class OverflowAnalyzer:
    """
    Analyzes bit-vector overflow and underflow conditions.

    Args:
        variables: List of bit-vector variables
        bit_width: Width of bit-vectors
    """

    def __init__(self, variables: List[z3.BitVecRef], bit_width: int):
        self.variables = variables
        self.bit_width = bit_width
        self.max_value = (1 << bit_width) - 1
        self.min_value = 0

    def _check_overflow(self, expr) -> OverflowType:
        """
        Check if an expression can cause overflow/underflow.

        Args:
            expr: Z3 expression to check

        Returns:
            OverflowType: Type of overflow detected
        """
        solver = z3.Solver()
        solver.add(expr)

        # Check for overflow
        overflow_possible = solver.check(expr > self.max_value) == z3.sat
        # Check for underflow
        underflow_possible = solver.check(expr < self.min_value) == z3.sat

        if overflow_possible and underflow_possible:
            return OverflowType.BOTH
        elif overflow_possible:
            return OverflowType.OVERFLOW
        elif underflow_possible:
            return OverflowType.UNDERFLOW
        return OverflowType.NONE

    def analyze_arithmetic_operations(self, formula) -> OverflowResults:
        """
        Analyze formula for potential overflow/underflow conditions.

        Args:
            formula: Z3 formula to analyze

        Returns:
            OverflowResults: Analysis results
        """
        results = OverflowResults()

        def visit(expr):
            if z3.is_add(expr):
                overflow_type = self._check_overflow(expr)
                if overflow_type in (OverflowType.OVERFLOW, OverflowType.BOTH):
                    results.overflow_count += 1
                if overflow_type in (OverflowType.UNDERFLOW, OverflowType.BOTH):
                    results.underflow_count += 1

                # Track affected variables
                for arg in expr.children():
                    if z3.is_const(arg):
                        results.affected_vars.add(str(arg))

            for child in expr.children():
                visit(child)

        visit(formula)

        # Calculate impact ratio
        if results.overflow_count + results.underflow_count > 0:
            total_vars = len(self.variables)
            affected_vars = len(results.affected_vars)
            results.impact_ratio = affected_vars / total_vars

        return results


class WrappedArithmetic:
    """
    Handles wrapped vs unwrapped arithmetic comparisons.

    Args:
        bit_width: Width of bit-vectors
    """

    def __init__(self, bit_width: int):
        self.bit_width = bit_width
        self.mask = (1 << bit_width) - 1

    def wrap_value(self, value: int) -> int:
        """Apply bit-vector wrapping to a value"""
        return value & self.mask

    def compare_arithmetic(self, formula, wrapped: bool = True) -> Dict[str, int]:
        """
        Compare results with and without wrapping.

        Args:
            formula: Original formula
            wrapped: Whether to use wrapped arithmetic

        Returns:
            Dict[str, int]: Comparison results
        """
        solver = z3.Solver()
        solver.add(formula)

        results = {}
        if solver.check() == z3.sat:
            model = solver.model()

            for decl in model.decls():
                value = model[decl].as_long()
                results[str(decl)] = (
                    self.wrap_value(value) if wrapped else value
                )

        return results


class ModelCounter:
    """Handles model counting operations"""

    def __init__(self, timeout_ms: int = 6000):
        self.timeout_ms = timeout_ms

    def is_sat(self, expression) -> bool:
        """Check if the expression is satisfiable"""
        solver = z3.Solver()
        solver.set("timeout", self.timeout_ms)
        solver.add(expression)
        return solver.check() == z3.sat

    def count_models(self, formula) -> int:
        """Count models using sharpSAT"""
        counter = BVModelCounter()
        counter.init_from_fml(formula)
        return counter.count_models_by_sharp_sat()


class AbstractionAnalyzer:
    """Analyzes different abstraction domains"""

    def __init__(self, formula, variables: List[z3.BitVecRef]):
        self.formula = formula
        self.variables = variables
        self.sa = BVSymbolicAbstraction()
        self.sa.init_from_fml(formula)
        self.overflow_analyzer = OverflowAnalyzer(variables, variables[0].size())

    def compute_false_positives(self, abs_formula) -> Tuple[bool, float]:
        """Compute false positive rate for an abstraction"""
        solver = z3.Solver()
        solver.add(z3.And(abs_formula, z3.Not(self.formula)))

        has_false_positives = solver.check() != z3.unsat
        if not has_false_positives:
            return False, 0.0

        mc = BVModelCounter()
        mc.init_from_fml(abs_formula)
        abs_count = mc.count_models_by_sharp_sat()

        mc_fp = BVModelCounter()
        mc_fp.init_from_fml(z3.And(abs_formula, z3.Not(self.formula)))
        fp_count = mc_fp.count_models_by_sharp_sat()

        return True, fp_count / abs_count

    def analyze_abstractions(self) -> Optional[AbstractionResults]:
        """Analyze all abstraction domains"""
        try:
            self.sa.interval_abs()
            self.sa.zone_abs()
            self.sa.octagon_abs()

            results = AbstractionResults()

            # Analyze each domain
            for domain, formula in [
                ("Interval", self.sa.interval_abs_as_fml),
                ("Zone", self.sa.zone_abs_as_fml),
                ("Octagon", self.sa.octagon_abs_as_fml)
            ]:
                has_fp, fp_rate = self.compute_false_positives(formula)
                logger.info(f"{domain} domain: {'has FP rate %.4f' % fp_rate if has_fp else 'no false positives'}")

                if domain == "Interval":
                    results.interval_fp_rate = fp_rate
                elif domain == "Zone":
                    results.zone_fp_rate = fp_rate
                else:
                    results.octagon_fp_rate = fp_rate

            # Analyze overflow/underflow
            results.overflow_results = self.overflow_analyzer.analyze_arithmetic_operations(self.formula)

            # Log overflow analysis results
            logger.info(f"Overflow count: {results.overflow_results.overflow_count}")
            logger.info(f"Underflow count: {results.overflow_results.underflow_count}")
            logger.info(f"Affected variables: {results.overflow_results.affected_vars}")
            logger.info(f"Impact ratio: {results.overflow_results.impact_ratio:.4f}")

            return results

        except Exception as e:
            logger.error(f"Error analyzing abstractions: {str(e)}")
            return None


def main():
    """Main entry point"""
    try:
        # Create test variables and formula
        bit_width = 8
        x, y, z = z3.BitVecs("x y z", bit_width)
        variables = [x, y, z]

        formula = FormulaGenerator(variables).generate_formula()
        counter = ModelCounter()

        if not counter.is_sat(formula):
            logger.info("Formula is unsatisfiable")
            return False

        # Count models
        model_count = counter.count_models(formula)
        logger.info(f"SharpSAT model count: {model_count}")

        # Analyze abstractions and overflow/underflow
        analyzer = AbstractionAnalyzer(formula, variables)
        results = analyzer.analyze_abstractions()

        # Compare wrapped vs unwrapped arithmetic
        wrapped_arithmetic = WrappedArithmetic(bit_width)
        wrapped_results = wrapped_arithmetic.compare_arithmetic(formula, wrapped=True)
        unwrapped_results = wrapped_arithmetic.compare_arithmetic(formula, wrapped=False)

        logger.info("Wrapped vs Unwrapped Arithmetic Comparison:")
        for var in wrapped_results:
            logger.info(f"{var}: wrapped={wrapped_results[var]}, unwrapped={unwrapped_results[var]}")

        if results:
            logger.info("Analysis completed successfully")
            return True

        return False

    except Exception as e:
        logger.error(f"Error in main: {str(e)}")
        return False


if __name__ == '__main__':
    main()
